name: My First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4

            -   name: welcome message
                run: echo "This is my first githb action"
        
            -   name: list
                run: ls

            -   name: Read file
                run: cat README.md 

